/** 港島理財報章：新手教學以逐步核對、官方來源與不推介個別基金為核心，採用可掃讀的報章欄目結構。 */
import { ArrowRight, BookOpenCheck, CircleHelp, ClipboardCheck, ExternalLink, FileSearch, Layers3, Scale, ShieldAlert } from "lucide-react";
import { Link } from "wouter";
import { Footer, Header } from "@/components/SiteFrame";
import { DataLedger } from "@/components/DataLedger";
import { useLocale } from "@/contexts/LocaleContext";
import { useFunds } from "@/lib/funds";
import "@/styles/guide.css";

type GuideStep = { number: string; title: string; body: string; prompt: string; icon: typeof FileSearch };

export default function Guide() {
  const { locale } = useLocale();
  const { document } = useFunds();
  const zh = locale === "zh-Hant";
  const steps: GuideStep[] = zh ? [
    { number: "01", title: "先找你的計劃與基金名稱", body: "從供款單、受託人網站或僱主資料找出基金名稱、計劃名稱及受託人。基金名稱相近時，計劃名稱是重要辨識資料。", prompt: "在基金資料庫搜尋名稱、供應商或計劃。", icon: FileSearch },
    { number: "02", title: "把同類基金放在一起看", body: "比較前先選資產類別或官方細分類。股票、債券、混合、保證及貨幣市場基金的目標與風險不同，不宜直接把不同類別的回報排在一起。", prompt: "先選類別，再看同儕排名。", icon: Layers3 },
    { number: "03", title: "用三個欄目慢慢核對", body: "查看 1 年、3 年及 5 年年率化回報、基金開支比率（FER）與風險級別。回報只供參考，往績不代表將來表現；收費與風險也應一併閱讀。", prompt: "把回報、FER、風險放在同一頁看。", icon: Scale },
    { number: "04", title: "翻開 KSID 與基金便覽", body: "受託人為新計劃成員提供強積金傻瓜包及主要計劃資料文件（KSID）。文件集中說明基金選擇、收費、風險及行政程序；需要深入了解時，應再查閱基金便覽與計劃文件。", prompt: "先讀概要，再開官方文件。", icon: BookOpenCheck },
    { number: "05", title: "認識 DIS，不把它當成保本", body: "未作基金選擇時，供款一般會按所屬計劃的預設投資策略（DIS）投資。DIS 包含核心累積基金與 65 歲後基金，並有自動降低風險及費用上限等特點；兩者均非保本或保證回報。", prompt: "分清「預設安排」與「保證回報」。", icon: CircleHelp },
    { number: "06", title: "定期檢視，毋須每日追看", body: "投委會建議計劃成員可每半年或一年檢視基金選擇。重點是核對你的計劃文件、持有基金與可理解的資料，而不是按短期升跌作出倉促判斷。", prompt: "設定半年或一年一次的核對提醒。", icon: ClipboardCheck },
  ] : [
    { number: "01", title: "Identify your scheme and fund", body: "Use your contribution statement, trustee site or employer materials to find the fund name, scheme name and trustee. The scheme name helps distinguish similarly named funds.", prompt: "Search by fund, provider or scheme in the database.", icon: FileSearch },
    { number: "02", title: "Compare like with like", body: "Select an asset class or official subcategory before comparing. Equity, bond, mixed assets, guaranteed and money market funds have different objectives and risks, so their returns should not be ranked together.", prompt: "Choose a category, then read the peer rank.", icon: Layers3 },
    { number: "03", title: "Check three fields together", body: "Read 1Y, 3Y and 5Y annualised returns together with the fund expense ratio (FER) and risk class. Returns are reference only and past performance does not indicate future performance; fees and risk matter too.", prompt: "Keep return, FER and risk on the same page.", icon: Scale },
    { number: "04", title: "Open the KSID and fact sheet", body: "Trustees provide a made-easy guide book and Key Scheme Information Document (KSID) for new members. These cover fund choices, fees, risks and administration; use fact sheets and scheme documents for deeper detail.", prompt: "Read the summary first, then the official documents.", icon: BookOpenCheck },
    { number: "05", title: "Understand DIS; do not treat it as guaranteed", body: "If no fund choice is made, contributions are generally invested under the scheme's Default Investment Strategy (DIS). It uses the Core Accumulation Fund and Age 65 Plus Fund, with automatic de-risking and fee caps; neither fund is capital- or return-guaranteed.", prompt: "Separate a default arrangement from a guarantee.", icon: CircleHelp },
    { number: "06", title: "Review regularly, not every day", body: "The IFEC suggests reviewing choices every six months or annually. Focus on verifying your documents, holdings and understandable information instead of reacting hastily to short-term moves.", prompt: "Set a six- or twelve-month check-in.", icon: ClipboardCheck },
  ];
  const content = zh ? { eyebrow: "強積金新手傻瓜包", title: "第一次睇 MPF，\n由核對開始。", intro: "這不是「買邊隻」指南，而是一條把公開資料、計劃文件與你的問題逐步對照的閱讀路線。", start: "開始搜尋基金", documents: "官方資料來源", documentsText: "你可從受託人取得 KSID、基金便覽及計劃文件；本站只協助你整理公開的比較欄目。", mpfa: "積金局：MPF 傻瓜包", ifec: "投委會：揀選 MPF 基金 5 步", dis: "積金局：預設投資策略", warning: "讀完教學後，仍請以受託人、基金便覽及積金局的最新官方資料為準。" } : { eyebrow: "MPF starter guide", title: "Your first MPF check\nstarts with verification.", intro: "This is not a " + "“which fund to buy” guide. It is a practical reading path that connects public data, scheme documents and your own questions.", start: "Start searching funds", documents: "Official documents", documentsText: "Your trustee can provide the KSID, fund fact sheets and scheme documents. This site helps organise public comparison fields only.", mpfa: "MPFA: Made-easy guide book", ifec: "IFEC: Five steps for MPF funds", dis: "MPFA: Default Investment Strategy", warning: "After this guide, verify any decision against the latest trustee documents, fund fact sheets and MPFA information." };
  const dateline = zh ? `第 01 期 · 資料截至 ${document?.as_of ?? "—"} · 公開資料閱讀指南` : `Issue 01 · Data as of ${document?.as_of ?? "—"} · Public-data reading guide`;
  return <div className="min-h-screen page-shell"><Header asOf={document?.as_of}/><main><section className="guide-hero"><div className="guide-hero-stamp">MPF / 101</div><div className="frame guide-hero-grid"><div><p className="eyebrow">{content.eyebrow}</p><p className="guide-dateline">{dateline}</p><h1>{content.title.split("\n").map((line) => <span key={line}>{line}</span>)}</h1><p>{content.intro}</p><Link href="/#fund-search" className="guide-primary-link">{content.start}<ArrowRight size={16}/></Link></div><aside><ShieldAlert size={23}/><strong>{zh ? "閱讀規則" : "Reading rule"}</strong><p>{zh ? "先理解資料定義，再作比較；排名及數字不等於建議。" : "Understand the data definitions before comparing; a rank or number is not a recommendation."}</p></aside></div></section><DataLedger document={document}/><section className="frame guide-steps" aria-label={content.eyebrow}><div className="guide-section-heading"><div><p className="eyebrow">{zh ? "逐步核對" : "A calm checklist"}</p><p className="guide-dateline guide-dateline-light">{dateline}</p></div><h2>{zh ? "6 步，建立自己的 MPF 閱讀習慣。" : "Six steps to build an MPF reading habit."}</h2></div><div className="guide-step-grid">{steps.map((step) => { const Icon = step.icon; return <article key={step.number} className="guide-step"><div className="guide-step-top"><span>{step.number}</span><Icon size={19}/></div><h3>{step.title}</h3><p>{step.body}</p><small>{step.prompt}</small></article>; })}</div></section><section className="frame guide-documents"><div><p className="eyebrow">{content.documents}</p><p className="guide-dateline guide-dateline-light">{zh ? "來源欄 · MPFA / IFEC 公開資料" : "Source desk · MPFA / IFEC public information"}</p><h2>{zh ? "工具之外，記得看原始文件。" : "Beyond the tool, read the source documents."}</h2><p>{content.documentsText}</p></div><div className="guide-source-links"><a href="https://www.mpfa.org.hk/en/info-centre/publications-articles/mpfa-articles/2024_9_25" target="_blank" rel="noreferrer">{content.mpfa}<ExternalLink size={14}/></a><a href={zh ? "https://www.ifec.org.hk/web/tc/young-adults/youth-investment/5-steps-mpf-funds.page" : "https://www.ifec.org.hk/web/en/young-adults/youth-investment/5-steps-mpf-funds.page"} target="_blank" rel="noreferrer">{content.ifec}<ExternalLink size={14}/></a><a href="https://www.mpfa.org.hk/en/mpf-investment/portfolio/default-investment-strategy" target="_blank" rel="noreferrer">{content.dis}<ExternalLink size={14}/></a></div></section><section className="frame guide-warning"><ShieldAlert size={20}/><p>{content.warning}</p></section></main><Footer asOf={document?.as_of}/></div>;
}
