/** 港島理財報章：不對稱資料專欄配以低調編輯邊欄，維持來源、時間與免責資訊可見。 */
import { BarChart3, BookOpen, ChevronRight, Languages, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useLocale } from "@/contexts/LocaleContext";
import { copy } from "@/lib/funds";
function Mark(){return <svg className="brand-mark" viewBox="0 0 40 40" aria-hidden="true"><rect width="40" height="40" rx="8" fill="#123c34"/><path fill="#dce9e2" d="M8 29V11h5l7 9 7-9h5v18h-5v-10l-7 9-7-9v10z"/><path fill="#55a89b" d="m27 23 3 3 6-7 2 2-8 9-5-5z"/></svg>}
export function Header({asOf,selectedCount=0}:{asOf?:string;selectedCount?:number}){const {locale,setLocale}=useLocale();const t=copy[locale];const [location]=useLocation();return <header className="site-header"><div className="frame header-inner"><Link href="/" className="brand" aria-label="MPF Fund Compare home"><Mark/><span className="brand-lockup"><b>MPF</b><span>Fund Compare</span></span></Link><nav className="nav-links" aria-label="Primary navigation"><Link href="/" className={location==="/"?"nav-link is-active":"nav-link"}>{t.home}</Link><Link href="/guide" className={location==="/guide"?"nav-link is-active":"nav-link"}><BookOpen size={15}/>{t.guide}</Link><Link href="/compare" className={location==="/compare"?"nav-link is-active":"nav-link"}><BarChart3 size={15}/>{t.compare}{selectedCount?<em>{selectedCount}</em>:null}</Link><button className="language-toggle" onClick={()=>setLocale(locale==="en"?"zh-Hant":"en")} aria-label="Switch language"><Languages size={15}/>{locale==="en"?"繁中":"EN"}</button></nav></div>{asOf?<div className="data-strip"><div className="frame"><span>{t.dataAsOf} <strong>{asOf}</strong></span><span><ShieldCheck size={13}/>{t.online}</span></div></div>:null}</header>;}
export function Footer({asOf}:{asOf?:string}){const {locale}=useLocale();const t=copy[locale];return <footer className="site-footer"><div className="frame footer-grid"><div className="footer-brand"><Mark/><span><b>MPF</b> Fund Compare</span></div><p>{t.disclaimer}</p><div className="footer-meta"><span>{t.privacy}</span>{asOf?<span>{t.updated}: {asOf}</span>:null}</div></div></footer>;}
export function TextLink({href,children}:{href:string;children:React.ReactNode}){return <Link className="text-link" href={href}>{children}<ChevronRight size={15}/></Link>;}
